using System.Diagnostics.Metrics;

namespace Nexus.Web.Modules.Observability;

/// <summary>
/// Domain metrics (§45 - "LLM latency, agent execution time, simulation
/// duration, queue depth, error rate" etc.) exposed via System.Diagnostics.Metrics
/// and picked up by OpenTelemetry's Meter listener (wired in Program.cs).
/// This closes the "tracing only, no metrics" gap - counters/histograms are
/// recorded at the exact point in the deterministic engines where the event
/// actually happens, not estimated after the fact.
/// </summary>
public class NexusMetrics
{
    public const string MeterName = "Nexus.Web";
    private readonly Meter _meter;

    public Counter<long> ScenariosSimulated { get; }
    public Histogram<double> SimulationDurationMs { get; }
    public Counter<long> SimulationJobsFailed { get; }
    public Counter<long> AlertsGenerated { get; }
    public Counter<long> MitigationStrategiesApproved { get; }
    public UpDownCounter<long> SimulationQueueDepth { get; }

    public NexusMetrics()
    {
        _meter = new Meter(MeterName, "1.0.0");
        ScenariosSimulated = _meter.CreateCounter<long>("nexus.scenarios.simulated", description: "Number of scenarios successfully simulated");
        SimulationDurationMs = _meter.CreateHistogram<double>("nexus.simulation.duration_ms", unit: "ms", description: "Wall-clock duration of a deterministic simulation run");
        SimulationJobsFailed = _meter.CreateCounter<long>("nexus.simulation_jobs.failed", description: "Background simulation jobs that threw during processing");
        AlertsGenerated = _meter.CreateCounter<long>("nexus.alerts.generated", description: "Alerts generated by AlertService, by severity");
        MitigationStrategiesApproved = _meter.CreateCounter<long>("nexus.mitigations.approved", description: "Mitigation strategies approved via human-in-the-loop workflow");
        SimulationQueueDepth = _meter.CreateUpDownCounter<long>("nexus.simulation_queue.depth", description: "Current depth of the background simulation job queue");
    }
}
